"""create initial tables

Revision ID: 44ff9bd74287
Revises:
Create Date: 2026-08-14 23:06:35.079312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ff9bd74287'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipient_profiles_email'), 'recipient_profiles', ['email'], unique=True)
    op.create_table('email_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('original_subject', sa.String(length=255), nullable=False),
    sa.Column('original_body', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_result', sa.JSON(), nullable=False),
    sa.Column('rewritten_subject', sa.String(length=255), nullable=False),
    sa.Column('rewritten_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_analyses_recipient_id'), 'email_analyses', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_analyses_recipient_id'), table_name='email_analyses')
    op.drop_table('email_analyses')
    op.drop_index(op.f('ix_recipient_profiles_email'), table_name='recipient_profiles')
    op.drop_table('recipient_profiles')
    # ### end Alembic commands ###
